from __future__ import annotations

from enum import IntEnum, IntFlag

from ._ffi import lib as _c


class ResultCode(IntEnum):
    OK = _c.EZO_OK
    ERR_INVALID_ARGUMENT = _c.EZO_ERR_INVALID_ARGUMENT
    ERR_BUFFER_TOO_SMALL = _c.EZO_ERR_BUFFER_TOO_SMALL
    ERR_TRANSPORT = _c.EZO_ERR_TRANSPORT
    ERR_PROTOCOL = _c.EZO_ERR_PROTOCOL
    ERR_PARSE = _c.EZO_ERR_PARSE


class CommandKind(IntEnum):
    GENERIC = _c.EZO_COMMAND_GENERIC
    READ = _c.EZO_COMMAND_READ
    READ_WITH_TEMP_COMP = _c.EZO_COMMAND_READ_WITH_TEMP_COMP
    CALIBRATION = _c.EZO_COMMAND_CALIBRATION


class DeviceStatus(IntEnum):
    UNKNOWN = _c.EZO_STATUS_UNKNOWN
    SUCCESS = _c.EZO_STATUS_SUCCESS
    FAIL = _c.EZO_STATUS_FAIL
    NOT_READY = _c.EZO_STATUS_NOT_READY
    NO_DATA = _c.EZO_STATUS_NO_DATA


class UARTResponseKind(IntEnum):
    UNKNOWN = _c.EZO_UART_RESPONSE_UNKNOWN
    DATA = _c.EZO_UART_RESPONSE_DATA
    OK = _c.EZO_UART_RESPONSE_OK
    ERROR = _c.EZO_UART_RESPONSE_ERROR
    OVER_VOLTAGE = _c.EZO_UART_RESPONSE_OVER_VOLTAGE
    UNDER_VOLTAGE = _c.EZO_UART_RESPONSE_UNDER_VOLTAGE
    RESET = _c.EZO_UART_RESPONSE_RESET
    READY = _c.EZO_UART_RESPONSE_READY
    SLEEP = _c.EZO_UART_RESPONSE_SLEEP
    WAKE = _c.EZO_UART_RESPONSE_WAKE
    DONE = _c.EZO_UART_RESPONSE_DONE


class UARTSequenceStep(IntEnum):
    NONE = _c.EZO_UART_SEQUENCE_STEP_NONE
    DATA = _c.EZO_UART_SEQUENCE_STEP_DATA
    CONTROL = _c.EZO_UART_SEQUENCE_STEP_CONTROL
    TERMINAL = _c.EZO_UART_SEQUENCE_STEP_TERMINAL


class ProductId(IntEnum):
    UNKNOWN = _c.EZO_PRODUCT_UNKNOWN
    PH = _c.EZO_PRODUCT_PH
    ORP = _c.EZO_PRODUCT_ORP
    EC = _c.EZO_PRODUCT_EC
    DO = _c.EZO_PRODUCT_DO
    RTD = _c.EZO_PRODUCT_RTD
    HUM = _c.EZO_PRODUCT_HUM


class ProductSupport(IntEnum):
    UNKNOWN = _c.EZO_PRODUCT_SUPPORT_UNKNOWN
    METADATA = _c.EZO_PRODUCT_SUPPORT_METADATA
    TYPED_READ = _c.EZO_PRODUCT_SUPPORT_TYPED_READ
    FULL = _c.EZO_PRODUCT_SUPPORT_FULL


class ProductTransport(IntEnum):
    UNKNOWN = _c.EZO_PRODUCT_TRANSPORT_UNKNOWN
    UART = _c.EZO_PRODUCT_TRANSPORT_UART
    I2C = _c.EZO_PRODUCT_TRANSPORT_I2C


class ProductDefaultState(IntEnum):
    UNKNOWN = _c.EZO_PRODUCT_DEFAULT_UNKNOWN
    DISABLED = _c.EZO_PRODUCT_DEFAULT_DISABLED
    ENABLED = _c.EZO_PRODUCT_DEFAULT_ENABLED
    QUERY_REQUIRED = _c.EZO_PRODUCT_DEFAULT_QUERY_REQUIRED


class ProductOutputSchema(IntEnum):
    UNKNOWN = _c.EZO_PRODUCT_OUTPUT_SCHEMA_UNKNOWN
    SCALAR_SINGLE = _c.EZO_PRODUCT_OUTPUT_SCHEMA_SCALAR_SINGLE
    PRIMARY_ONLY = _c.EZO_PRODUCT_OUTPUT_SCHEMA_PRIMARY_ONLY
    QUERY_REQUIRED = _c.EZO_PRODUCT_OUTPUT_SCHEMA_QUERY_REQUIRED


class ProductCapability(IntFlag):
    MEASUREMENT = _c.EZO_PRODUCT_CAP_MEASUREMENT
    CALIBRATION = _c.EZO_PRODUCT_CAP_CALIBRATION
    TEMPERATURE_COMPENSATION = _c.EZO_PRODUCT_CAP_TEMPERATURE_COMPENSATION
    SALINITY_COMPENSATION = _c.EZO_PRODUCT_CAP_SALINITY_COMPENSATION
    PRESSURE_COMPENSATION = _c.EZO_PRODUCT_CAP_PRESSURE_COMPENSATION
    OUTPUT_SELECTION = _c.EZO_PRODUCT_CAP_OUTPUT_SELECTION
    CALIBRATION_TRANSFER = _c.EZO_PRODUCT_CAP_CALIBRATION_TRANSFER
    DATA_LOGGING = _c.EZO_PRODUCT_CAP_DATA_LOGGING
    MEMORY_RECALL = _c.EZO_PRODUCT_CAP_MEMORY_RECALL
    RANGE_SELECTION = _c.EZO_PRODUCT_CAP_RANGE_SELECTION
    PROBE_CONFIGURATION = _c.EZO_PRODUCT_CAP_PROBE_CONFIGURATION
    TDS_CONFIGURATION = _c.EZO_PRODUCT_CAP_TDS_CONFIGURATION
    SCALE_SELECTION = _c.EZO_PRODUCT_CAP_SCALE_SELECTION


class ProductCommandFamily(IntFlag):
    ACQUISITION = _c.EZO_PRODUCT_FAMILY_ACQUISITION
    CALIBRATION = _c.EZO_PRODUCT_FAMILY_CALIBRATION
    CALIBRATION_TRANSFER = _c.EZO_PRODUCT_FAMILY_CALIBRATION_TRANSFER
    IDENTITY = _c.EZO_PRODUCT_FAMILY_IDENTITY
    DEVICE_CONTROL = _c.EZO_PRODUCT_FAMILY_DEVICE_CONTROL
    PROTOCOL_CONTROL = _c.EZO_PRODUCT_FAMILY_PROTOCOL_CONTROL


class MeasurementField(IntEnum):
    UNKNOWN = _c.EZO_MEASUREMENT_FIELD_UNKNOWN
    PH = _c.EZO_MEASUREMENT_FIELD_PH
    ORP = _c.EZO_MEASUREMENT_FIELD_ORP
    TEMPERATURE = _c.EZO_MEASUREMENT_FIELD_TEMPERATURE
    CONDUCTIVITY = _c.EZO_MEASUREMENT_FIELD_CONDUCTIVITY
    TOTAL_DISSOLVED_SOLIDS = _c.EZO_MEASUREMENT_FIELD_TOTAL_DISSOLVED_SOLIDS
    SALINITY = _c.EZO_MEASUREMENT_FIELD_SALINITY
    SPECIFIC_GRAVITY = _c.EZO_MEASUREMENT_FIELD_SPECIFIC_GRAVITY
    DISSOLVED_OXYGEN = _c.EZO_MEASUREMENT_FIELD_DISSOLVED_OXYGEN
    OXYGEN_SATURATION = _c.EZO_MEASUREMENT_FIELD_OXYGEN_SATURATION
    RELATIVE_HUMIDITY = _c.EZO_MEASUREMENT_FIELD_RELATIVE_HUMIDITY
    DEW_POINT = _c.EZO_MEASUREMENT_FIELD_DEW_POINT
    AIR_TEMPERATURE = _c.EZO_MEASUREMENT_FIELD_AIR_TEMPERATURE


class PHCalibrationLevel(IntEnum):
    NONE = _c.EZO_PH_CALIBRATION_NONE
    ONE_POINT = _c.EZO_PH_CALIBRATION_ONE_POINT
    TWO_POINT = _c.EZO_PH_CALIBRATION_TWO_POINT
    THREE_POINT = _c.EZO_PH_CALIBRATION_THREE_POINT


class PHCalibrationPoint(IntEnum):
    MID = _c.EZO_PH_CALIBRATION_POINT_MID
    LOW = _c.EZO_PH_CALIBRATION_POINT_LOW
    HIGH = _c.EZO_PH_CALIBRATION_POINT_HIGH


class PHExtendedRange(IntEnum):
    DISABLED = _c.EZO_PH_EXTENDED_RANGE_DISABLED
    ENABLED = _c.EZO_PH_EXTENDED_RANGE_ENABLED


class ORPExtendedScale(IntEnum):
    DISABLED = _c.EZO_ORP_EXTENDED_SCALE_DISABLED
    ENABLED = _c.EZO_ORP_EXTENDED_SCALE_ENABLED


class RTDScale(IntEnum):
    UNKNOWN = _c.EZO_RTD_SCALE_UNKNOWN
    CELSIUS = _c.EZO_RTD_SCALE_CELSIUS
    KELVIN = _c.EZO_RTD_SCALE_KELVIN
    FAHRENHEIT = _c.EZO_RTD_SCALE_FAHRENHEIT


class ECOutputMask(IntFlag):
    CONDUCTIVITY = _c.EZO_EC_OUTPUT_CONDUCTIVITY
    TOTAL_DISSOLVED_SOLIDS = _c.EZO_EC_OUTPUT_TOTAL_DISSOLVED_SOLIDS
    SALINITY = _c.EZO_EC_OUTPUT_SALINITY
    SPECIFIC_GRAVITY = _c.EZO_EC_OUTPUT_SPECIFIC_GRAVITY


class ECCalibrationPoint(IntEnum):
    DRY = _c.EZO_EC_CALIBRATION_DRY
    SINGLE_POINT = _c.EZO_EC_CALIBRATION_SINGLE_POINT
    LOW_POINT = _c.EZO_EC_CALIBRATION_LOW_POINT
    HIGH_POINT = _c.EZO_EC_CALIBRATION_HIGH_POINT


class DOOutputMask(IntFlag):
    MG_L = _c.EZO_DO_OUTPUT_MG_L
    PERCENT_SATURATION = _c.EZO_DO_OUTPUT_PERCENT_SATURATION


class DOSalinityUnit(IntEnum):
    MICROSIEMENS = _c.EZO_DO_SALINITY_UNIT_MICROSIEMENS
    PPT = _c.EZO_DO_SALINITY_UNIT_PPT


class DOCalibrationPoint(IntEnum):
    ATMOSPHERIC = _c.EZO_DO_CALIBRATION_ATMOSPHERIC
    ZERO = _c.EZO_DO_CALIBRATION_ZERO


class HUMOutputMask(IntFlag):
    HUMIDITY = _c.EZO_HUM_OUTPUT_HUMIDITY
    AIR_TEMPERATURE = _c.EZO_HUM_OUTPUT_AIR_TEMPERATURE
    DEW_POINT = _c.EZO_HUM_OUTPUT_DEW_POINT
