COMMAND_GENERIC = "generic"
COMMAND_READ = "read"
COMMAND_READ_WITH_TEMP_COMP = "read_with_temp_comp"
COMMAND_CALIBRATION = "calibration"

I2C_STATUS_UNKNOWN = 0
I2C_STATUS_SUCCESS = 1
I2C_STATUS_FAIL = 2
I2C_STATUS_NOT_READY = 3
I2C_STATUS_NO_DATA = 4

UART_RESPONSE_UNKNOWN = 0
UART_RESPONSE_DATA = 1
UART_RESPONSE_OK = 2
UART_RESPONSE_ERROR = 3
UART_RESPONSE_OVER_VOLTAGE = 4
UART_RESPONSE_UNDER_VOLTAGE = 5
UART_RESPONSE_RESET = 6
UART_RESPONSE_READY = 7
UART_RESPONSE_SLEEP = 8
UART_RESPONSE_WAKE = 9
UART_RESPONSE_DONE = 10
